apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: itelleria/demo
    newTag: "4.0"

resources:
  - deployment.yaml
  - service.yaml
  - ../argocd/end-to-end-tests-postsync-hook.yaml

configMapGenerator:
  - name: database
    literals:
      - database-url="jdbc:url-to-database"
      - database-username="username-database"

secretGenerator:
  - name: database
    literals:
      - database-password="password-database"